name: GennarioFramework
version: '${project.version}'
main: cz.gennario.gennarioframework.Main
api-version: '1.20'
folia-supported: true
author: Gennario
softdepend:
  - packetevents
  - ProtocolLib
  - Nexo
  - ItemsAdder
  - Oraxen
  - PlaceholderAPI